name: New release

# triggers the workflow when a tag is created
on:
  create:
    ref: refs/tags/*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: act10ns/slack@v1
        name: notify-slack
        with:
          status: 'START'
          env:
            SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
          if: always()
